// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "honest-ivory-thicket-app-superbased-cowork-backe",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "set -a; [ -f .env ] && . ./.env; set +a; export APP_ID='39b5702d-b758-4a8c-a761-16bc7d30f986' APP_LABEL='Superbased Cowork Backend' USER_ALIAS='honest-ivory-thicket'; sh -c 'set -a; [ -f .env ] && . ./.env; set +a; export PORT=\"${COWORKER_BE_PORT:-3100}\"; bun run src/index.ts'"
      ],
      "cwd": "/Users/mini/code/superbased/coworker/superbased-be",
      "out_file": "/Users/mini/code/superbased/coworker/superbased-be/apps/logs/honest-ivory-thicket-app-superbased-cowork-backe-out.log",
      "error_file": "/Users/mini/code/superbased/coworker/superbased-be/apps/logs/honest-ivory-thicket-app-superbased-cowork-backe-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
